export const CART_FETCH_REQUEST = "CART_FETCH_REQUEST";
export const CART_FETCH_SUCCESS = "CART_FETCH_SUCCESS";
export const CART_FETCH_FAILURE = "CART_FETCH_FAILURE";
export const UPDATE_CART = "UPDATE_CART";
export const UPDATE_ITEM_QUANTITY = "UPDATE_ITEM_QUANTITY";
export const DELETE_PRODUCT = "DELETE_PRODUCT";

export const SHOP_INFO_FETCH_REQUEST = "SHOP_INFO_FETCH_REQUEST";
export const SHOP_INFO_FETCH_SUCCESS = "SHOP_INFO_FETCH_SUCCESS";
export const SHOP_INFO_FETCH_FAILURE = "SHOP_INFO_FETCH_FAILURE";

