export const ORDER_DETAIL_FETCH_REQUEST = "ORDER_DETAIL_FETCH_REQUEST";
export const ORDER_DETAIL_FETCH_SUCCESS = "ORDER_DETAIL_FETCH_SUCCESS";
export const ORDER_DETAIL_FETCH_FAILURE = "ORDER_DETAIL_FETCH_FAILURE";