export const SHOW_LOADER = "SHOW_LOADER"
export const STOP_LOADER = "STOP_LOADER"
export const SET_AUTH_USER = "SET_AUTH_USER"
export const SET_SHOP_SLUG = "SET_SHOP_SLUG"
export const UNSET_AUTH_USER = "UNSET_AUTH_USER"
export const SET_USER_DATA = "SET_USER_DATA"