export const PROFILE_FETCH_REQUEST = "PROFILE_FETCH_REQUEST";
export const PROFILE_UPDATE_REQUEST = "PROFILE_FETCH_REQUEST";
export const PROFILE_FETCH_SUCCESS = "PROFILE_FETCH_SUCCESS";
export const PROFILE_FETCH_FAILURE = "PROFILE_FETCH_FAILURE";